import {describe,it,expect} from 'vitest';
import {parseModel,designCoverage,designFocus,defaultReviewCatalog,planNextQuestions,saveReview,renderDesignFocusMap,renderDesignMap} from '../src/index.js';
const source="version: '0.1'\nproduct: {id: p, capabilities: [{id: c, behaviors: [{id: b, realized_by: [impl]}]}, {id: sibling}]}\ncomponents: [{id: impl, description: full canonical detail}]\n";
describe('design coverage workflow',()=>{
 it('includes unstarted scopes without silently writing conclusions',()=>{const m=parseModel(source),before=JSON.stringify(m),c=designCoverage(m);expect(c.scopes.map(s=>s.target)).toEqual(['p','c','sibling']);expect(c.total).toBe(3*defaultReviewCatalog.length);expect(c.concluded).toBe(0);expect(c.conclusionsComplete).toBe(false);expect(JSON.stringify(m)).toBe(before);const p=planNextQuestions(m,{phase:'shape',focusIds:['c']});expect([p.primary,...p.related,...p.deferred].some(q=>q?.targetId==='c'&&q.code.startsWith('REVIEW_UNREVIEWED:'))).toBe(true);});
 it('distinguishes documented deferral from resolution and incomplete draft',()=>{const record={id:'r',target:'c',perspective:'contracts',status:'deferred' as const,rationale:'外部仕様待ち',owner:'team',residual_risk:'互換性が未確定',revisit_when:'仕様確定時'};const saved=saveReview(source,record);expect(designCoverage(parseModel(saved),'c')).toMatchObject({concluded:1,resolved:0});const draft=saveReview(saved,{...record,residual_risk:undefined});expect(designCoverage(parseModel(draft),'c').concluded).toBe(0);});
 it('narrows a capability without siblings and exposes boundary connections and every field',()=>{const focus=designFocus(parseModel(source),'c');expect(focus.entities.map(e=>e.id)).toEqual(['c','b','impl']);expect(focus.boundary.map(e=>e.id)).toEqual(['p']);expect(focus.entities.find(e=>e.id==='impl')?.data.description).toBe('full canonical detail');expect(focus.edges.some(e=>e.from==='p'&&e.to==='c')).toBe(true);});
 it('narrows a perspective to explicit supporting elements without hiding outside links',()=>{const saved=saveReview(source,{id:'r',target:'c',perspective:'logical_responsibilities',status:'applicable',owner:'team',rationale:'この責務で実現する',addresses:['impl']});const f=designFocus(parseModel(saved),'c','logical_responsibilities');expect(f.entities.map(e=>e.id)).toEqual(['c','impl']);expect(f.boundary.map(e=>e.id)).toContain('b');expect(()=>designFocus(parseModel(saved),'c','missing')).toThrow();});
 it('renders the focused map from the same IDs, with boundary context and without unrelated siblings',()=>{const svg=renderDesignFocusMap(parseModel(source),'c').svg;expect(svg).toContain('data-node="impl"');expect(svg).toContain('data-node="p"');expect(svg).toContain('範囲外への接続');expect(svg).not.toContain('data-node="sibling"');});
 it('shows review coverage on the legacy map',()=>{expect(renderDesignMap(parseModel(source)).svg).toContain('未結論');});
});
