import {afterEach,expect,it,vi} from 'vitest';
import {installMapGestures,type MapTransform} from '../site/map-gestures.js';
let cleanup=()=>{};
afterEach(()=>{cleanup();document.body.innerHTML='';});
function setup(){const canvas=document.createElement('div');document.body.append(canvas);let state:MapTransform={scale:1,x:0,y:0};const host={get:()=>({...state}),set:(next:MapTransform)=>{state=next;},begin:vi.fn()};const gestures=installMapGestures(canvas,host);cleanup=gestures.destroy;
 const pointer=(type:string,id:number,x:number,y:number)=>{const event=new MouseEvent(type,{bubbles:true,cancelable:true,clientX:x,clientY:y,button:0});Object.defineProperties(event,{pointerId:{value:id},pointerType:{value:'touch'}});(type==='pointerdown'?canvas:window).dispatchEvent(event);};return {canvas,pointer,get:host.get};}
it('keeps taps still, pans with one finger, and suppresses swipe clicks but permits keyboard actions',()=>{const {canvas,pointer,get}=setup();const click=vi.fn();canvas.addEventListener('click',click);pointer('pointerdown',1,100,100);pointer('pointermove',1,102,102);expect(get()).toEqual({scale:1,x:0,y:0});pointer('pointerup',1,102,102);canvas.dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));expect(click).toHaveBeenCalledTimes(1);pointer('pointerdown',1,100,100);pointer('pointermove',1,130,140);expect(get()).toEqual({scale:1,x:30,y:40});pointer('pointerup',1,130,140);canvas.dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));expect(click).toHaveBeenCalledTimes(1);canvas.dispatchEvent(new MouseEvent('click',{bubbles:true,detail:0}));expect(click).toHaveBeenCalledTimes(2);});
it('anchors pinch at its moving midpoint and rebases smoothly from two fingers to one',()=>{const {pointer,get}=setup();pointer('pointerdown',1,100,100);pointer('pointerdown',2,200,100);pointer('pointermove',1,50,120);pointer('pointermove',2,250,120);expect(get()).toEqual({scale:2,x:-150,y:-80});pointer('pointerup',2,250,120);pointer('pointermove',1,60,150);expect(get()).toEqual({scale:2,x:-140,y:-50});pointer('pointercancel',1,60,150);pointer('pointermove',1,900,900);expect(get()).toEqual({scale:2,x:-140,y:-50});});
it('clamps pinch scale and drops stale pointers on blur',()=>{const {pointer,get}=setup();pointer('pointerdown',1,0,0);pointer('pointerdown',2,100,0);pointer('pointermove',2,1000,0);expect(get().scale).toBe(4);pointer('pointermove',2,1,0);expect(get().scale).toBe(.1);window.dispatchEvent(new Event('blur'));const before=get();pointer('pointermove',2,200,0);expect(get()).toEqual(before);pointer('pointerdown',3,20,20);pointer('pointermove',3,30,30);expect(get()).toEqual({...before,x:before.x+10,y:before.y+10});});
