import {beforeEach,it,expect,vi} from 'vitest';
import {installReviews} from '../site/reviews.js';
import {parseModel,reviewSummary,reviewStatuses} from '../src/index.js';
vi.mock('@archmodel/core',()=>import('../src/index.js'));
beforeEach(()=>{document.body.innerHTML='';HTMLDialogElement.prototype.showModal=function(){this.open=true;};HTMLDialogElement.prototype.close=function(){this.open=false;};});
const input=(id:string,value:string)=>{document.querySelector<HTMLInputElement>(`#review-${id}`)!.value=value;};
const save=()=>document.querySelector('#review-form')!.dispatchEvent(new Event('submit',{cancelable:true}));
function setup(){let source="version: '0.1'\nproduct: {id: p, capabilities: [{id: c}]}\n";const ui=installReviews({source:()=>source,model:()=>parseModel(source),replace:s=>{source=s;}});ui.open('p');return {ui,model:()=>parseModel(source),change:()=>{source+='\n# changed';}};}
it('saves draft exclusions, reports missing reasons, then resolves with complete grounds',()=>{const h=setup();expect([...document.querySelectorAll<HTMLOptionElement>('#review-status option')].map(o=>o.value)).toEqual(reviewStatuses);input('status','not_applicable');save();expect(document.querySelector('#review-error')!.textContent).toContain('rationale');expect(reviewSummary(h.model(),'p').resolved).toBe(0);input('owner','team');input('rationale','対象外の理由');input('assumptions','前提1\n前提2');input('revisit','利用方法が変わったとき');save();expect(h.model().reviews).toHaveLength(1);expect(reviewSummary(h.model(),'p').resolved).toBe(1);input('target','c');document.querySelector('#review-target')!.dispatchEvent(new Event('change'));expect(document.querySelector('.review-summary')!.textContent).toContain('未開始');expect(document.querySelector<HTMLSelectElement>('#review-status')!.value).toBe('unreviewed');});
it('starts tracking without fabricating records and blocks stale saves',()=>{const h=setup();document.querySelector<HTMLButtonElement>('#start-review')!.click();expect(reviewSummary(h.model(),'p').tracked).toBe(true);expect(h.model().reviews).toEqual([]);h.change();save();expect(document.querySelector('#review-error')!.textContent).toContain('モデルが変更されました');expect(h.model().reviews).toEqual([]);});
