import {describe,it,expect} from 'vitest';
import {dump} from 'js-yaml';
import {parseModel,validateModel,defaultReviewCatalog,reviewRows,reviewSummary,reviewGaps,saveReview,startReview,suggestReviewId,deleteEntity,mergeContribution,completeness,toYaml,toMarkdown,planNextQuestions} from '../src/index.js';
import type {DesignReview,ReviewStatus} from '../src/index.js';
const base="version: '0.1'\nproduct: {id: p, capabilities: [{id: c}]}\nqualities: [{id: q, attribute: availability}]\n";
const record=(patch:Partial<DesignReview>={}):DesignReview=>({id:'review-p',perspective:'quality.availability',target:'p',status:'not_applicable',rationale:'ローカルで利用するため常時稼働するAPIを持たない',owner:'team',assumptions:['オフライン利用のみ'],revisit_when:'Webサービスとして提供するとき',...patch});
const withReviews=(reviews:DesignReview[],extra:Record<string,unknown>={})=>base+dump({...extra,reviews});
const errors=(source:string)=>parseModel(source).diagnostics.filter(d=>d.severity==='error');
describe('perspective reviews',()=>{
 it('keeps custom perspective IDs separate from entity IDs while merging',()=>{const source=base+dump({review_catalog:[{id:'p',name:'Custom perspective'}]});const merged=parseModel(mergeContribution(source,source));expect(merged.reviewCatalog).toHaveLength(1);expect(merged.entities.filter(e=>e.id==='p')).toHaveLength(1);});
 it('keeps legacy documents untracked rather than calling them complete',()=>{const m=parseModel(base);expect(reviewSummary(m)).toMatchObject({tracked:false,total:0,complete:false});expect(reviewSummary(m,'p')).toMatchObject({tracked:false,resolved:0,complete:false});expect(reviewRows(m,'p').every(r=>r.status==='unreviewed')).toBe(true);expect(validateModel(m).some(d=>d.code.startsWith('REVIEW_'))).toBe(false);});
 it('starts tracking all perspectives as unreviewed without manufacturing records',()=>{const m=parseModel(startReview(base,'p'));expect(m.reviews).toEqual([]);expect(reviewSummary(m,'p').counts.unreviewed).toBe(defaultReviewCatalog.length);expect(validateModel(m).filter(d=>d.code==='REVIEW_UNREVIEWED')).toHaveLength(defaultReviewCatalog.length);});
 it('does not inherit a parent exclusion into its child',()=>{const m=parseModel(withReviews([record()]));expect(reviewRows(m,'p').find(r=>r.perspective.id==='quality.availability')?.resolved).toBe(true);expect(reviewRows(m,'c').find(r=>r.perspective.id==='quality.availability')?.status).toBe('unreviewed');});
 it.each(['rationale','owner','assumptions','revisit_when'] as const)('does not resolve an exclusion without %s',key=>{const r=record();delete r[key];expect(reviewGaps(r)).toContain(key);const m=parseModel(withReviews([r]));expect(errors(toYaml(m))).toEqual([]);expect(validateModel(m).some(d=>d.code==='REVIEW_INCOMPLETE')).toBe(true);expect(reviewSummary(m,'p').resolved).toBe(0);});
 it('requires design references for applicable and rejects references on exclusions',()=>{expect(reviewGaps(record({status:'applicable'}))).toContain('addresses');expect(reviewGaps(record({status:'applicable',addresses:['q']}))).toEqual([]);expect(reviewGaps(record({addresses:['q']}))).toContain('addresses_not_applicable');});
 it('keeps a well documented deferral visible and unresolved',()=>{const r=record({status:'deferred',residual_risk:'連続停止中は手動対応する'});expect(reviewGaps(r)).toEqual([]);expect(reviewGaps({...r,residual_risk:undefined})).toContain('residual_risk');const m=parseModel(withReviews([r]));expect(reviewSummary(m,'p')).toMatchObject({resolved:0,complete:false,counts:{deferred:1}});expect(validateModel(m).some(d=>d.code==='REVIEW_DEFERRED')).toBe(true);});
 it('does not suppress existing requirement or verification gaps',()=>{const m=parseModel(withReviews([record()]));expect(validateModel(m).map(d=>d.code)).toEqual(expect.arrayContaining(['NO_REALIZATION','UNCOVERED','NO_PARENT']));});
 it('separates completed review from verified implementation',()=>{const reviews=defaultReviewCatalog.map((p,i)=>record({id:`r-${i}`,perspective:p.id}));const m=parseModel(withReviews(reviews));expect(reviewSummary(m,'p').complete).toBe(true);expect(completeness(m,'p')).toMatchObject({review:{complete:true},verified:false});});
 it('round trips records and retains rationale, assumptions and risk in Markdown',()=>{const source=withReviews([record({status:'deferred',residual_risk:'manual-recovery'})]);const m=parseModel(source);expect(parseModel(toYaml(m)).reviews).toEqual(m.reviews);const markdown=toMarkdown(m);expect(markdown).toContain('manual-recovery');expect(markdown).toContain('revisit_when');expect(markdown).toContain('assumptions');});
 it('accepts custom catalog entries and includes them in the checklist',()=>{const m=parseModel(withReviews([record({perspective:'business_rules'})],{review_catalog:[{id:'business_rules',name:'業務ルール'}]}));expect(m.diagnostics.filter(d=>d.severity==='error')).toEqual([]);expect(reviewRows(m,'p')).toHaveLength(defaultReviewCatalog.length+1);});
 it.each([
  [withReviews([record({target:'missing'})]),'UNKNOWN_REFERENCE'],
  [withReviews([record({perspective:'missing'})]),'UNKNOWN_REFERENCE'],
  [withReviews([record({status:'applicable',addresses:['missing']})]),'UNKNOWN_REFERENCE'],
  [withReviews([record({id:'p'})]),'DUPLICATE_ID'],
  [withReviews([record(),record({id:'r2'})]),'DUPLICATE_REVIEW'],
  [withReviews([record({status:'bad' as ReviewStatus})]),'ENUM'],
  [withReviews([],{review_catalog:[{id:'actors',name:'duplicate'}]}),'DUPLICATE_ID'],
  [withReviews([],{review_scopes:['missing']}),'UNKNOWN_REFERENCE']
 ])('rejects invalid references and records', (source,code)=>{expect(errors(source).map(d=>d.code)).toContain(code);});
 it('saves records without changing the design graph and keeps IDs stable',()=>{const source=saveReview(base,record());const m=parseModel(source);expect(m.entities).toEqual(parseModel(base).entities);expect(m.edges).toEqual(parseModel(base).edges);expect(suggestReviewId(m,'p','quality.availability')).toBe('review-p');expect(parseModel(saveReview(source,record({rationale:'更新した理由'}))).reviews).toHaveLength(1);});
 it('retains review metadata when deleting unrelated entities and merges scopes',()=>{const source=withReviews([record()],{review_catalog:[{id:'business_rules',name:'業務ルール'}],review_scopes:['p']});const after=parseModel(deleteEntity(source,'q'));expect(after.reviews).toEqual([record()]);expect(after.reviewCatalog).toHaveLength(1);const merged=parseModel(mergeContribution(source,"version: '0.1'\nproducts: [{id: other}]\nreview_scopes: [other]\n"));expect(merged.reviewScopes).toEqual(['p','other']);expect(merged.reviews).toEqual([record()]);});
 it('reopens the review when an addressed design element is removed',()=>{const source=withReviews([record({status:'applicable',addresses:['q']})]);const m=parseModel(deleteEntity(source,'q'));expect(m.reviews?.[0]).toMatchObject({status:'in_review',addresses:[]});expect(reviewSummary(m,'p').resolved).toBe(0);expect(errors(toYaml(m))).toEqual([]);});
 it('removes only records for a deleted target and keeps children unreviewed',()=>{const m=parseModel(deleteEntity(startReview(withReviews([record()]),'c'),'p'));expect(m.reviews).toEqual([]);expect(m.reviewScopes).toEqual(['c']);expect(reviewSummary(m,'c').counts.unreviewed).toBe(defaultReviewCatalog.length);});
 it('rejects conflicting scope/perspective judgments during merge',()=>{const a=withReviews([record()]),b=withReviews([record({rationale:'different'})]);expect(()=>mergeContribution(a,b)).toThrow();});
 it('offers distinct questions for unreviewed perspectives without changing the model',()=>{const m=parseModel(startReview(base,'p')),before=JSON.stringify(m);const p=planNextQuestions(m,{phase:'shape'});const codes=[p.primary,...p.related,...p.deferred].filter(q=>q?.code.startsWith('REVIEW_UNREVIEWED:')).map(q=>q!.code);expect(new Set(codes).size).toBe(defaultReviewCatalog.length);expect(JSON.stringify(m)).toBe(before);});
});
