export type LaneLanguage='en'|'ja';
export const laneCopy:Record<string,[string,string,string]>={
 product:['Product','プロダクト','誰にどんな価値を提供するか、目的と対象範囲を定義します。'],
 capability:['Capability','ケイパビリティ','利用者が実現できることを定義し、振る舞いと品質要求につなげます。'],
 quality:['Quality','品質要求','達成すべき品質を、目標値や条件とともに定義します。'],
 policy:['Policy','ポリシー','設計・実装・運用で守る共通ルールと適用先を定義します。'],
 decision:['Decision','設計判断','選んだ設計方針と、その理由・代償を記録します。'],
 component:['Component','論理コンポーネント','振る舞いや品質要求を実現する責務のまとまりです。'],
 realization:['Realization','技術実現','実行環境、コード、IaC、リソースや検証などの具体的な実現先です。'],
 behavior:['Behavior','振る舞い','きっかけ、処理、結果を定義します。具体例はScenarioに追加します。'],
 verification:['Verification','検証','要求を満たしているか確認する方法と結果を定義します。'],
 evidence:['Evidence','証跡','検証結果を裏付ける記録を定義します。'],
 contract:['Contract','契約','APIやイベントの仕様を定義します。'],
 scenario:['Scenario','シナリオ','振る舞いの具体例や受入条件を、選んだ記述形式で表します。'],
 reliability:['Reliability','信頼性','可用性、耐障害性、復旧性、許容するデータ損失などを定義します。'],
 performance:['Performance & Scalability','性能・拡張性','応答時間、処理量、容量、負荷の増加への対応を定義します。'],
 security:['Security & Privacy','セキュリティ・プライバシー','認証・認可、情報保護、完全性、個人情報保護の要求を定義します。'],
 operability:['Operability','運用性','監視、可観測性、監査証跡、障害対応の要求を定義します。'],
 maintainability:['Maintainability','保守性','変更・解析・テストを容易にするための要求を定義します。'],
 usability:['Usability & Accessibility','使用性・アクセシビリティ','分かりやすさ、操作性、利用上の障壁への要求を定義します。'],
 compatibility:['Compatibility','互換性・相互運用性','外部システムとの連携、共存、互換性を定義します。'],
 portability:['Migration & Deployment','移行・配備・移植性','データ移行、環境変更、リリース、ロールバックの要求を定義します。'],
 safety:['Safety','安全性','人や環境への危害を防ぐための要求を定義します。'],
 decision_quality:['Quality','品質','品質要求を満たすために選んだ設計と理由を記録します。'],
 cost:['Cost','コスト','費用の制約を踏まえた構成選択とトレードオフを記録します。'],
 delivery:['Delivery','デリバリー','提供時期、開発・リリース方法について選んだ方針を記録します。'],
 ownership:['Ownership','責任分担','担当チームや責任の境界について選んだ方針を記録します。'],
 runtime:['Runtime','実行構成','実行方式、配置、基盤の選定理由を記録します。'],
 security_baseline:['Security Baseline','セキュリティ基準','TLSや秘密情報の管理など、共通で守るセキュリティ基準です。'],
 logging_standard:['Logging Standard','ログ標準','ログ形式、必須項目、マスキングなどの共通ルールです。'],
 iam_policy:['IAM Policy','アクセス管理','最小権限、管理者認証、権限付与・削除などのルールです。'],
 naming_tagging:['Naming / Tagging','命名・タグ付け','リソースの名前や、担当・環境などのタグ付けルールです。'],
 data_protection:['Data Protection','データ保護','暗号化、保存期間、削除などのデータ保護ルールです。'],
 compliance_rules:['Compliance Rules','コンプライアンス','適用される法令、契約、社内規程に対応するルールです。'],
 logical_application:['Application','アプリケーション','アプリケーションに分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 logical_domain:['Domain','ドメイン','ドメインに分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 logical_data:['Data','データ','データに分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 logical_interface:['Interface','インターフェース','インターフェースに分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 logical_platform:['Platform','基盤','基盤に分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 logical_contract:['Contract','契約','契約に分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 technical_runtime:['Runtime','実行環境','実行環境に分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 technical_resource:['Resource','リソース','リソースに分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 technical_network:['Network','ネットワーク','ネットワークに分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 technical_data:['Data','データ基盤','データ基盤に分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 technical_directory:['Directory','ディレクトリ','ディレクトリに分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 technical_module:['Module','モジュール','モジュールに分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 technical_source:['Source','ソース','ソースに分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 technical_iac:['IaC','構成コード','構成コードに分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 technical_deployment:['Deployment','配備','配備に分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 technical_verification:['Verification','検証','検証に分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 technical_evidence:['Evidence','証跡','証跡に分類された要素をまとめます。＋からこの種類の要素を追加できます。'],
 unspecified:['Uncategorized','未分類','カテゴリが未設定の項目です。編集でカテゴリを設定できます。']
};
export function laneLabel(key:string,language:LaneLanguage='en'){return laneCopy[key]?.[language==='ja'?1:0]??key;}
