/** Shared labels for the map, editor and inspector. */
export const fieldLabels:Record<string,string>={type:'記述形式：Type',name:'名称：Name',owner:'担当：Owner',status:'状態：Status',purpose:'目的：Purpose',primary_users:'利用者：Users',user_value:'価値：Value',scope:'対象範囲：Scope',out_of_scope:'対象外：Out of scope',actor:'利用者：Actor',inputs:'入力：Inputs',outputs:'出力：Outputs',trigger:'きっかけ：Trigger',outcomes:'結果：Outcomes',specification:'内容：Specification',kind:'種類：Kind',responsibilities:'責務：Responsibilities',service:'サービス：Service',location:'場所：Location',attribute:'品質属性：Attribute',requirement:'品質要求：Requirement',target:'目標：Target',unit:'単位：Unit',rules:'ルール：Rules',method:'検証方法：Method',level:'検証レベル：Level',use_cases:'ユースケース：Use case',commands:'コマンド：Command',events:'イベント：Event',guarantees:'保証：Guarantees',constraints:'制約：Constraints',category:'分類：Category',context:'背景：Context',decision:'決定：Decision',reason:'理由：Reason',trade_off:'トレードオフ：Trade-off',provider:'提供元：Provider',result:'結果：Result'};
export const relationLabels:Record<string,string>={has:'配下に含める',realizedBy:'実現先',implementedBy:'実装先',verifiedBy:'検証先',appliesTo:'適用する',affects:'影響する',evidencedBy:'証跡',uses:'利用する',provides:'提供する',consumes:'受け取る'};

export const scenarioFormats:Record<string,string>={gherkin:'Gherkin',state_transition:'状態遷移',timing:'タイミング',example:'データ例',batch:'バッチ',iot:'IoT',async_event:'非同期イベント',text:'自由記述'};

export const qualityCategories:Record<string,string>={reliability:'信頼性',performance:'性能・拡張性',security:'セキュリティ・プライバシー',operability:'運用性',maintainability:'保守性',usability:'使用性・アクセシビリティ',compatibility:'互換性・相互運用性',portability:'移行・配備・移植性',safety:'安全性'};
export const qualityAttributeCategory:Record<string,string>={availability:'reliability',resilience:'reliability',recoverability:'reliability',scalability:'performance',privacy:'security',observability:'operability',audit:'operability',testability:'maintainability',accessibility:'usability',interoperability:'compatibility',migration:'portability',deployment:'portability'};
export const decisionCategories:Record<string,string>={quality:'品質',cost:'コスト',delivery:'デリバリー',ownership:'責任分担',runtime:'実行構成'};
export const qualityCategory=(attribute:unknown)=>typeof attribute==='string'?(qualityAttributeCategory[attribute]??attribute):'unspecified';

export const policyCategories:Record<string,string>={security_baseline:'Security Baseline',logging_standard:'Logging Standard',iam_policy:'IAM Policy',naming_tagging:'Naming / Tagging',data_protection:'Data Protection',compliance_rules:'Compliance Rules'};

Object.assign(fieldLabels,{description:'説明：Description',extensions:'拡張情報：Extensions',preconditions:'事前条件：Preconditions',failure_behaviors:'失敗時の振る舞い：Failure behaviors',side_effects:'副作用：Side effects',sli:'品質指標：SLI',rto:'復旧時間目標：RTO',rpo:'復旧時点目標：RPO',risk:'リスク：Risk',title:'見出し：Title',alternatives:'代替案：Alternatives',decision_status:'判断の状態：Decision status',interfaces:'インターフェース：Interfaces',data:'データ：Data',template:'構成パターン：Template',environment:'環境：Environment',public:'外部公開：Public',authentication:'認証方式：Authentication',deployment_strategy:'配備方式：Deployment strategy',observability:'監視・可観測性：Observability',collected_at:'取得日時：Collected at'});
